# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  - id: cargo-fmt
    name: cargo-fmt
    language: system
    entry: cargo +nightly fmt --
    types: [text, rust]
