# See https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "clinvoice-schema"
version = "0.9.2"
authors = ["Iron-E <code.iron.e@gmail.com>"]
description = "Data structures for CLInvoice."

edition = "2021"
license = "GPL3"
readme = "README.md"
repository = "https://www.github.com/Iron-E/clinvoice-schema"

[dependencies]
clinvoice-finance = {branch = 'release/0.4', git = 'https://github.com/Iron-E/clinvoice-finance'}

chrono = {features = ["serde"], version = "0.4"}
futures = "0.3"
humantime-serde = "1"
lazy_static = "1"
serde = {optional = true, version = "1"}
thiserror = "1"

[dev-dependencies]
pretty_assertions = "1"

[features]
default = []
serde = ["clinvoice-finance/serde", "serde/derive"]
