mod restorable_serde;

#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

use super::Id;

/// A functoinal part of the [`Organization`][organization].
///
/// The [`Organization`][organization] that the [`Department`] is for is not stored in the entity,
/// as the [`Organization`][organization] using Winvoice is configured elsewhere and referenced as
/// necessary.
///
/// [organization]: super::Organization
#[cfg_attr(feature = "serde", derive(Deserialize, Serialize))]
#[derive(Clone, Default, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Department
{
	/// The reference number of this [`Department`], which is unique among all [`Department`]s.
	///
	/// Should be generated by a database, and never altered once assigned.
	pub id: Id,

	/// The name of the [`Department`].
	pub name: String,
}
